### ISSUE TITLE
Bug on development environment when clicking many times to login as test student

### ISSUE THREAD

**Issue by mssiegel** [mssiegel/frempco-client#105]
There is a minor bug on the development environment. If a user rapidly clicks the test student link shortcut many times, they'll be logged in as a student.  But their name on the student page will be different than the one on the teachers page.  

Most likely this is an issue that can be solved by throttling. Because this only happens on the development environment, I think is a minor bug. But we should eventually look into this to make sure it doesn't hide any larger bugs. 

![image](https://user-images.githubusercontent.com/29524485/160286117-55a7ee86-43ff-42c6-b585-443527238e8f.png)

**Comment by karlrez** [comment]
I see our normal visit students classroom button already has a throttle function, but I am not sure that is exactly what we want.
When I spam click to visit the student classroom my additional clicks are calling  still calling the function (just delaying the function call) and we get an error:

![image](https://user-images.githubusercontent.com/47090434/160668570-a19880f2-1943-41bc-b274-4fec48f79b2a.png)

Based off a bit of reading on this: https://stackoverflow.com/questions/25991367/difference-between-throttling-and-debouncing-a-function , if we just change our existing throttle function to debounce we could fix this issue. But I will try get a PR up for the dev link before I touch the production one.

**Comment by mssiegel** [comment]
We should still use a Throttle. Throttling fires the first call and ignores the later ones. In contract, Debouncing ignores the first calls and only fires the last one. 
Throttling is the right version for pressing a button. As you want it to fire immediately and ignore the next button clicks. 
If we have console errors, then it means we are not implementing the Throttle correctly. We should fix it, but we should continue using the Throttle.

**Comment by mssiegel** [comment]
I replicated that error on both prod and localhost. I spam clicked the Vist Students Room button. localhost provided this improved error messaging.
![image](https://user-images.githubusercontent.com/29524485/160728211-80397637-bf25-4ba2-b9f3-e2124337097a.png)

**Comment by karlrez** [comment]
Makes sense! I did find a solution with Throttle by adding settings for specifying when the function is invoked:

![image](https://user-images.githubusercontent.com/47090434/160744136-d85a7c70-9aa8-4cf6-9a13-fba96e47e638.png)

By not having trailing set to false, it always fired one additional time.
If this looks good for you, I'll update my existing PR.

**Comment by mssiegel** [comment]
Oh nice!!! This is awesome! Yes, i see in[ Lodash docs for Throttle ](https://lodash.com/docs/4.17.15#throttle) that trailing defaults to true.
This fix looks makes sense to me! Update your existing PR to fix for both real user and test user.
