### ISSUE TITLE
Center the chatbox on mobile

### ISSUE THREAD

**Issue by mssiegel** [mssiegel/frempco-client#112]
The chatbox should be centered on mobile. But there is some sort of empty space on the left hand side.
 
![image](https://user-images.githubusercontent.com/29524485/161434521-e7e9014a-94aa-4d2e-a2b9-c9cfcee4f826.png)

**Comment by zachlankton** [comment]
This is caused by `pl: 2` in

https://github.com/mssiegel/frempco-client/blob/895aa1ce2099f8c35f0ea893d60c7b4cac306777/src/components/shared/Layout.tsx#L10

Do you want the left padding removed?

Or do you want right padding added to match?

**Comment by mssiegel** [comment]
Thanks for finding the source of the padding!! I started looking into it to see which would be better for your question. And then ended up just making a PR.
