### ISSUE TITLE
Limit name size, align remove user button

### ISSUE THREAD

**Issue by karlrez** [mssiegel/frempco-client#118]
I noticed our 'x' moves depending on the name size:

![image](https://user-images.githubusercontent.com/47090434/161662829-a70a2ff3-5b53-4a11-bf71-cb83fc5bde31.png)

And then while testing this I saw I can really mess with it:

![image](https://user-images.githubusercontent.com/47090434/161662126-fd66acba-fcd9-42a8-86e4-afb4b3947a9a.png)

I think when the student enters the classroom we should put a limit on the size of name they can input

**Comment by mssiegel** [comment]
Hahahah this is funny! Thanks for catching this! We could do a quick PR to limit the max text allowed in the student name input. 

Aligning the Xs should wait until Issue #116 is done. As that one will improve the whole unpaired students list component. Whatever PR resolves that issue might end up aligning the Xs as part of it.
