### ISSUE TITLE
Chatbox Width looks funny

### ISSUE THREAD

**Issue by mssiegel** [mssiegel/frempco-client#120]
When a teacher unpairs a student pair, the chatbox looks cutoff on the students page. This bug was caused by https://github.com/mssiegel/frempco-client/pull/115

![image](https://user-images.githubusercontent.com/29524485/162227237-05488620-32b7-4be7-aae0-ef26e653b90c.png)

This feels tricky to solve because there are so many scenarios. There is the student chatbox, the chatbox on homepage, and the chatbox shown on teachers page. It has to look right on all of them both on mobile and desktop. Whether the student is still chatting or the chat has ended. 

For the Teachers chatbox on mobile, it doesn't matter whether or not there is empty space on the sides. But the students chatbox on mobile should be nearly the whole horizontal width of the screen to make it easier to type messages.

**Comment by karlrez** [comment]
I'll fiddle around with this and try find a fix with media queries or MUI breakpoints

**Comment by mssiegel** [comment]
Thanks @karlrez. I think this will be solved by adding a  media query to student chatbox for screen width >= 500px to be width 100%.  Because as shown in PR #115 it has a max width of 500px.
