### ISSUE TITLE
Improve paired students list on TeachersPage

### ISSUE THREAD

**Issue by mssiegel** [mssiegel/frempco-client#121]
The TeachersPage's `PairedStudentList` component can be improved. It uses a Material UI `List` which limits the css and the styling we can use. We should refactor and replace the `List` entirely with our own code. 

This design shows what an improved version might look like:
![image](https://user-images.githubusercontent.com/29524485/162624275-21de32e3-5eab-4561-8bba-392d8f875b44.png)

**Comment by karlrez** [comment]
![image](https://user-images.githubusercontent.com/47090434/167310495-d69a27b5-6d6d-457f-b0aa-197bd7c56856.png)

The only difference I see right now is the button backgrounds. Were you hoping to have the styling for everything else left as is after refactoring?

**Comment by mssiegel** [comment]
Styling changes:
1) The button backgrounds
2) The displayed chat is a light grey background color and isn't sunk in anymore
3) By removing the List and using our own css  this Paired Students list will match the width of the Unpaired Students List

**Comment by karlrez** [comment]
ok got it. I'll start on adding those changes.
