### ISSUE TITLE
Add types to backend `database.js`

### ISSUE THREAD

**Issue by mssiegel** [mssiegel/frempco-client#136]
There are backend objects for `classrooms`, `teachers`, `students`, and `chatIds`.  We should add a file called types.ts and define these types.  Having types will prevent us from making errors when writing new code. 

https://github.com/mssiegel/frempco-server/blob/main/services/database.ts#L3-L6

**Comment by mssiegel** [comment]
@karlrez Thanks for taking this! I think it'd be a good idea to do a smaller PR first with just a type for `classrooms`. Then I can review it and provide feedback. And after thats merged you can then do the other 3 objects.

**Comment by karlrez** [comment]
@mssiegel apologies, I had a few things come up and I probably won't get to it for a while. I'll unassign myself and you can go ahead for this one.

**Comment by karlrez** [comment]
Looks like this is still available, I will go ahead with it
