### ISSUE TITLE
The list of paired students should be its own scrollable component

### ISSUE THREAD

**Issue by mssiegel** [mssiegel/frempco-client#42]
The list of paired students should be its own scrollable component, separate from the Chatbox.  Scrolling down the chatbox should not scroll down the list of paired students. Similiarly, scrolling down the list of Paired Students should not scroll down the chatbox. 

![image](https://user-images.githubusercontent.com/29524485/151895903-cae025fc-fad0-422d-aa4c-f5c5c93fbb8a.png)

**Comment by zachlankton** [comment]
Took a quick look at the code:

https://github.com/mssiegel/frempco-client/blob/761c799b973f018f8ce0423c61a12555e27884f9/src/components/pages/TeachersPage/index.tsx#L90-L103

Moving `PairedStudentsList` inside the grid item that contains the `UnpairedStudentsList` as shown below

```javascript
      <Grid container spacing={2}>
        <Grid item xs={12} md={5}>
          <UnpairedStudentsList socket={socket} />
          <PairedStudentsList
            studentChats={studentChats}
            setDisplayedChat={setDisplayedChat}
          />
        </Grid>

        <Grid item xs={12} md={7}>
          {showDisplayedChat()}
        </Grid>
      </Grid>
```

Results in the following:

![Issue5Test](https://user-images.githubusercontent.com/2927894/154855519-ab82c979-ca0b-45e5-99c5-e9967892ab6d.PNG)

On smaller width viewports the chat pushes to the bottom:

![Issue5TestSmall](https://user-images.githubusercontent.com/2927894/154855595-e3484b7e-f7d9-4a51-ad3a-ff5ddd9281a3.PNG)
