### ISSUE TITLE
Display students real name on Students Page

### ISSUE THREAD

**Issue by mssiegel** [mssiegel/frempco-client#51]
When a student enters their classroom, they see the words "Hello student!"  The greeting should include the student's name.

How to implement: 
Currently, the student enters their real name on the Homepage. Instead, the student should enter their name when they enter the Student's Page. 

![image](https://user-images.githubusercontent.com/29524485/155915647-26233983-8215-41bf-a4cb-b617028a6b6c.png)

**Comment by zachlankton** [comment]
If it is ok I would like to discuss some options on this one.  I believe consecutive modals, (first one for the classname -> page navigation to class -> second modal for the user name) is not a great user experience.

I have 2 ideas.

We can leave the single modal as is and persist the student name to our context and reuse it anywhere in the app.  This would be consistent with where we might be headed with issue #53 

OR

We can move the modal into the student chat page.

Either way, the goal is to maintain the user experience of only having to be prompted once for information as opposed to twice.

**Comment by mssiegel** [comment]
Yes, you opened my eyes! Two consecutive modals is weird and extraneous. Keeping the context as is and persisting the student name with context seems the most straigthforward to me.

The student needs to enter the name of the classroom they're going to on the homepage. So I don't see how the single modal can be moved to the student page.
