### ISSUE TITLE
Highlight Student Pair

### ISSUE THREAD

**Issue by mssiegel** [mssiegel/frempco-client#52]
The Displayed Chat on the Teacher's Page always corresponds to just one student pair in `<PairedStudentsList/>`. That student pair should be highlighted in `<PairedStudentsList/>`, perhaps with a fancier border.

Furthermore, the paired student's names could be bolded and colored red and blue. Because that'll match how their names appear in the displayed chat.

**Comment by karlrez** [comment]
i will take this one

**Comment by zachlankton** [comment]
Hello! @karlrez, My apologies, I was in the middle of working on all of the issues last night and just now saw this morning you posted.

**Comment by karlrez** [comment]
Hi @zachlankton, no worries at all! I did not even start on it yet.
