### ISSUE TITLE
Remove Home link on production

### ISSUE THREAD

**Issue by mssiegel** [mssiegel/frempco-client#53]
The Home link in the [Layout Navbar](https://github.com/mssiegel/frempco-client/blob/main/src/components/shared/Layout.tsx) can easily cause bugs!! There is no benefit to any real life user clicking the Home link. But the Home link is useful for developers.  So the Home link should only appear on development, similar to current links on the bottom of the Homepage [see screenshot below].  

**Example bugs caused by Home link:**
**Student:** if a logged-in student clicks the Home link they'll return to the homepage. But their socket will **still** be connected, allowing them to login again and appear twice on the Teacher's page.

**Teacher:** If a logged-in teacher clicks the Home link, they'll return to the homepage but their socket will **still** be connected. Students will still be able to login, but the teacher won't see them as the teacher is on the homepage. This will cause bugs. 

![image](https://user-images.githubusercontent.com/29524485/155917488-9361a205-3a82-4f2b-9fae-5063a17deed0.png)
![image](https://user-images.githubusercontent.com/29524485/155918376-52965ef2-7712-4aa2-8583-d4b857a01137.png)

**Comment by zachlankton** [comment]
I've actually been thinking about this problem and I believe the root issue is navigation in general.  Even if we remove the Home button, the user can still click the back button in their browser and the same bug described exists.

Next.js has a way to hook into the router using [routeChangeStart](https://nextjs.org/docs/api-reference/next/router#routerevents) that will allow us to detect when the user navigates away using any method. (Easy)

Eventually, I think we will want to look into using our context to store some state about the user that persists across site navigation.  This would be info like student name and active chat.  That way if they accidently hit back, they can hit forward and return to their chat intact, with history. (Medium)

**Comment by mssiegel** [comment]
Oh I love this routeChangeStart!!! Its perfect!!!!!! Yes, go ahead and implement it! It's a better solution!!!

Regarding the Medium solution, it is technically possible to have them return to the chat. But I think that users won't care much if they're able to do so. So implementing this would be lower priority than the other many features we have.
