### ISSUE TITLE
Ability to Remove Unpaired student from classroom

### ISSUE THREAD

**Issue by zachlankton** [mssiegel/frempco-client#54]
If a student is abusing the character naming feature or joins with a silly name the teacher should be able to "boot" that student from the class.

**Comment by mssiegel** [comment]
I feel this should be split into two separate and independent issues.  1) Teacher can kick out an unpaired student.  2) Teacher can end a chat (thereby putting those students back to unpaired).

**Comment by zachlankton** [comment]
Added a second issue #60 for unpairing.  This issue will be used to track removing an unpaired student entirely from the classroom
