### ISSUE TITLE
Prevent student from double clicking to enter Frempco

### ISSUE THREAD

**Issue by mssiegel** [mssiegel/frempco-client#65]
If a student double clicks really fast on the Enter Classroom button, they will appear twice on the Teacher's page.

We should add a Throttle so the function to visit Students page can only be fired max of once every few seconds. 
Libraries such as UnderScore or Lodash have prebuilt Throttle functions we can use. 

![image](https://user-images.githubusercontent.com/29524485/156929814-94c58bd9-c84c-43aa-8bca-c4a982ce4ea5.png)

**Comment by zachlankton** [comment]
I wonder if a double check on the server in the `addStudentToClassroom` to see if the student is already in the classroom would be the easiest way to accomplish this?

https://github.com/mssiegel/frempco-server/blob/aaf2e3ca7197516273f985aae7166b089bae8a86/services/database.js#L31-L39

**Comment by mssiegel** [comment]
Its the client that has the bug. A double clicked button should still only send one message to the server. 
Though handling this case in the server will solve the issue, adding a solution on the server will hide the fact that the client's button has the bug.

**Comment by zachlankton** [comment]
Understood, just as general side note though, any student with coding knowledge could figure out how to send messages to the websocket server from the browser console.  The following code works quite well for that:

```javascript
t = document.createElement("script")
t.src = "https://cdn.socket.io/4.4.1/socket.io.min.js"
document.head.appendChild(t)
t = io("http://localhost:4000") // replace this with the correct url
t.emit("new student entered", {classroom: "apple", student: "JoeASDF" })

```

**Comment by mssiegel** [comment]
Ooooh that's interesting. I hadn't realized it would be so easy!!!
But I think very few will have the coding skills. I feel its more likely a disruptive student will just act out in class and disrupt the class that way. 
When students prove us wrong, and someone starts hacking, that's when we'll address it.
