### ISSUE TITLE
Add avatar beside name in chat

### ISSUE THREAD

**Issue by karlrez** [mssiegel/frempco-client#76]
Adding an avatar like these:

![image](https://user-images.githubusercontent.com/47090434/157176007-c95919be-f4f3-4516-be8f-afd253cf8cda.png)

**Comment by mssiegel** [comment]
I wonder if this will be helpful, or if its unnecessary. Ariella always uses the Set Character List button to change the character list to ones from the books her class reads. Perhaps Ariella prefer a way to customize the icons to match the character names she uses. 
Before building this, we should get Ariella's input.

**Comment by mssiegel** [comment]
@karlrez I think we can close this issue.  I searched [Google for sample scripts](https://www.google.com/search?q=script+play&tbm=isch&ved=2ahUKEwjejdSXoND2AhVcrXIEHfYHCdsQ2-cCegQIABAA&oq=script+play&gs_lcp=CgNpbWcQAzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEOgcIIxDvAxAnOgcIABCxAxBDOggIABCABBCxAzoKCAAQsQMQgwEQQzoECAAQQ1DUA1iKCmCUC2gAcAB4AIABaYgBjwOSAQM1LjGYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=Pco0Yp77LtzaytMP9o-k2A0&bih=951&biw=2048#imgrc=jV2bJXnRwn2s1M).  No dialogue in those scripts have icons next to the names. So I don't think our dialogue should either.

If a teacher asks for this, we can create a new issue. But for now, I think this issue should be closed.

**Comment by karlrez** [comment]
@mssiegel sorry! I completely missed this. Thats great you mentioned the sample scripts, its gives me a better idea of how the students are using the app. I agree, we can skip this for now.
