### ISSUE TITLE
Add test classroom

### ISSUE THREAD

**Issue by mssiegel** [mssiegel/frempco-client#77]
Till now we've been using "apple" as our test classroom. This issue is to add another classroom named "test". Give it the password of "111".  This will make it obvious to any future person who joins our team that we have a test classroom. 

On the homepage on local development, there are shortcuts to visit the test classroom. Replace "apple" with "test" in those url links.

**Comment by zachlankton** [comment]
Karl identified that no update was necessary to the links as the links use a `sampleClassroomName` variable that refers to the first class in the `classrooms.json` array.  Simply adding the test classroom to the top was all that was needed.
