### ISSUE TITLE
Create a Custom List Component / Refactor Teacher Page Lists

### ISSUE THREAD

**Issue by zachlankton** [mssiegel/frempco-client#83]
## Create a Custom List Component and refactor the lists on the teacher page to use it.

Currently, the Material UI List Component does not lend itself to a great developer experience and the code is not very nice.  Creating a custom list component that allows us to do more of what we want with ideally less code is the task of this issue.

## References:

https://github.com/mssiegel/frempco-client/pull/72#discussion_r822690295

> Using the Material UI List component is sorta holding us hostage with the CSS styles we can use. I think we could still use the Material UI List for now. But eventually, as we add more features to this component, we'll need to replace the List with our own customized component.

https://github.com/mssiegel/frempco-client/pull/71#pullrequestreview-904423036

> The Material UI List component is holding us hostage. We can't build a user friendly design if we use it. We'll need to replace it with our own customized component. But I think doing so should be its own separate PR that just replaces the List.

**Comment by mssiegel** [comment]
Using PowerPoint, I made this nicer looking mock for the unpaired students list:
![image](https://user-images.githubusercontent.com/29524485/160292627-141d36c3-84ec-426b-8e1c-3730cafffa9d.png)
