### ISSUE TITLE
Further improvements of server Typescript

### ISSUE THREAD

**Issue by mssiegel** [mssiegel/frempco-client#89]
As documented here: https://blog.appsignal.com/2022/01/19/how-to-set-up-a-nodejs-project-with-typescript.html
1) Add ts-node
2) Add ES lint

A previous Typescript project I used had this in package.json:
![image](https://user-images.githubusercontent.com/29524485/158070409-e3e57662-c968-445c-a8c4-dfb1caf5181c.png)

If I remember correctly, what it was doing is on any change of a file, it just transpiles that file into Typescript. In contrast, I think our current package.json is setup to transpile all the backend files on every change.

**Comment by mssiegel** [comment]
Also, we add TypeScript to the list of technologies in the backend Readme.

**Comment by zachlankton** [comment]
I'm not sure the above is true... I ran a quick test with our newly merged typescript server and I believe `tsc` is already optimized to only build files that have changed.

When I first start the server from a fresh clone and run `npm run dev`, all files get built as you would expect as can be observed by the timestamps below:

![first](https://user-images.githubusercontent.com/2927894/158274185-68652be3-6a70-40f6-8f0a-816430b6a719.PNG)

But after I make a change to just the index file only the time stamp on that file updates, suggesting that `tsc` is only transpiling the index file and none of the others.

![second](https://user-images.githubusercontent.com/2927894/158274548-a5a12782-e4b6-444f-8c1b-96a276729a03.PNG)

That all being said, I am fine with changing this to the version you posted above if it works better for the purposes of this project.
