### ISSUE TITLE
Phone goes dark when left untouched

### ISSUE THREAD

**Issue by mssiegel** [mssiegel/frempco-client#90]
From Ariella:
"For the kids working on the phone, it seems that when their screen went dark, they were automatically kicked out."

Towards the end of Ariella's video, some students were sending messages on their phones. It was appearing on their screens and not on their peers.  This was caused by their phones going dark and getting "disconnected".  @mssiegel replicated this behavior on his own phone. 

Phones going dark sounds like a common problem for any real-time chat application. Perhaps StackOverflow will have ideas on how to solve this.

**Comment by karlrez** [comment]
@zachlankton tried out the demo, works good. If it reduces errors with the app, I think it would greatly improve the user experience. For myself, when I use chat apps I turn off my screen between messages and constantly refresh the page to check for new messages, I think a lot of users may follow the same behaviour when trying out Frempco.

**Comment by mssiegel** [comment]
Interesting thing here! I tried Zach's demo and it worked. I then tried the regular Frempco website and that worked also! I let my android samsung go dark using the regular Frempco website and it was still connected. It still received messages when dark. When I unlocked the screen I was still in the classroom.  Strange.

Around two minutes later I looked back at the Teachers page and I'd been disconnected. So it seems that on production, it doesn't kick you out right away when your phone goes dark, but rather waits a bit.

**Comment by mssiegel** [comment]
Okay, I tested this on Frempco **production** with my android phone and a stopwatch.
**First try** was was with phone student unpaired: Took **59 seconds** after phone went dark to disconnect
**Second try** student was paired and received zero messages:  Took **59 seconds** after phone went dark to disconnect
**Third try** student was paired and peer was sending messages:  Took **59 seconds** after phone went dark to disconnect

There is a clear pattern of 59 seconds AFTER the Android phone goes dark to disconnect. If I unlock my my phone screen anytime between them, I remain logged in as usual and will receive any messages sent to me during the time my phone went dark.

**Comment by mssiegel** [comment]
Several browsers now have a [WakeLock feature](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API). This keeps the mobile browser alive! YESS!!! 
According to [CanIUse](https://caniuse.com/?search=screen%20wake%20lock), its supported on Chrome, Samsung, but not on Safari.

**Comment by zachlankton** [comment]
On my iphone it's practically instant.  Worse yet, phone doesn't have to go dark or be put to sleep, just switching apps is enough.

**Comment by mssiegel** [comment]
Great comment about the iPhone Zach. I tried it on my wife's iPhone just now and was kicked out a few seconds after it went dark.

@zachlankton  Can you make the PR for your solution with sessionStorage?
Let's give a 2 minute window. I picked that number sort of at random. I feel like it gives enough time for a user to see their phone went dark and unlock it. While also being short enough to disconnect a user who really did leave permanently. 

Separately, we should still add the WakeLock Feature to prevent any browser which has it from going to sleep. 

I'll make a PR for the WakeLock feature. Zach will make a PR for sessionStorage with the 2 minute window. This will solve this critical issue!

**Comment by mssiegel** [comment]
Actually @zachlankton I got a bug by trying it on your demo http://208.87.134.100:3000/ with these instructions:
1. Paired up student on my laptop with student on my android phone. 
2. Closed the laptop student browser.  Closed the android phone browser.
3. The teacher still saw both students on the Teachers Page.

I feel there might be a lot of edge cases we might not consider. Trying to solve this now might open a can of worms. Perhaps we could just inform the teachers that phones going dark will disconnect their phones. That might depriorize this issue enough for us to work all our other Github issues and come back to this one much later. 

@zachlankton What do you think?

**Comment by zachlankton** [comment]
Yes, currently the teacher will see them in their respective state (paired or unpaired) until the timeout expires and actually removes them.  

In the unpaired case it prevents the teacher from seeing the student leave and come back again unnecessarily (think network interruptions or failures, which are currently not handled at all and crash the server when the user comes back online... https://www.youtube.com/watch?v=C6AjFQuHaxM) **_The session fix also addresses the server crashing._**

In the paired case, it prevents students from becoming unpaired if they go offline, switch apps, or their phone goes dark.  This gives them an opportunity to log back in a pick up where they left off.

I have updated the demo to timeout after 30 seconds so we can play around with the functionality without waiting so long.

I also added some event handling for when the user goes offline to gracefully let that user know.

Here is a video demo demonstrating the latest update: https://www.youtube.com/watch?v=bEQzt6C4-t4

Can still also access at http://208.87.134.100:3000/

**Comment by mssiegel** [comment]
Zach, I looked at your frontend/backend PRs. The idea of user sessions is technically amazing and will solve the issues of 1) server crashing and 2) phone going dark, going offline, switching apps. 
User sessions willl improve the **user experience**. 

However, the tradeoff of user sessions is it'll hurt the **developer experience**. 1) incongnito browsers takes more effort. 2) the backend code becomes more complex when we start handling sessions. 

So we have the tradeoff of user experience vs developer experience. 

We're at an early stage where we want to move fast, experiment fast, try out new ideas, and get fast feedback from teachers. Developer speed is critical. Anything that slows down developer speed reduces our speed of trying out new ideas. 

At this early stage of ours, speed of trying out new ideas is more important than a good user experience. Therefore, I think we should avoid user sessions.

**Comment by mssiegel** [comment]
To permanently prevent the server from crashing, I made draft PR: https://github.com/mssiegel/frempco-server/pull/18

**Comment by zachlankton** [comment]
Fair enough, I will close for now.
