### ISSUE TITLE
Mobile copying/pasting into Google Doc comes out as black & white

### ISSUE THREAD

**Issue by mssiegel** [mssiegel/frempco-client#91]
From Ariella's video, students who copied/pasted into Google Docs from their phone saw black & white text. The student who copied/pasted from their laptop saw it appeared correctly.

Moshe replicated this in an [example Google Doc](https://docs.google.com/document/d/1thyYPCPif0xXgFKL6QkBqIFh0uenpZkO2DZQwfMZSn4/edit). 

Before working on this, we need to speak to Ariella or other teachers to find out if this issue matters to them.

**Comment by karlrez** [comment]
Tried this out on my Samsung Android device and got the same. Seems my clipboard saves everything as plain text. The only solution I came across online was to download a third party clipboard to your phone, but this might be different for other phones.

**Comment by mssiegel** [comment]
That observation about the plain text was spot on! On my Samsung Android, Google Docs only gives the option to "paste" and it comes out as the plain text. In contrast, I copied/pasted from my Samsung Android into my phone's Gmail and the formatting displayed perfectly. 

The ideal solution would be making our own "copy to clipboard" button that somehow retain its formatting no matter where its copied into. 
Otherwise, we can tell the teachers to have their students email them to maintain the formatting.

**Comment by karlrez** [comment]
I fiddled around a bit with creating a "copy to clipboard" button which did solve the issue of not copying with formatting. However, I got the same result as well, no formatting when pasting into Google docs, but displays perfect when pasting into Gmail. So sending the conversation via email is doable.

**Comment by mssiegel** [comment]
Most text, such as all books and essays are black/white. So I think teachers won't care much if students submit their chats as black/white. 
@karlrez, Can you assign yourself this issue? Can you make a PR to add the copy to clipboard button? Try to get it to copy with formatting as much possible, but if you can't that's okay. 

Once that button is made we can close this issue. If teachers later ask for how their students can submit colored and formatted chats, we would open a new issue for it then.

**Comment by karlrez** [comment]
The only thing I was missing was the background red color, but everything else seemed to copy fine. 

Also, do you have any suggestions on the location of the button? I was thinking on the left of the character input:
![image](https://user-images.githubusercontent.com/47090434/159069800-68298b34-7851-4af2-b3a1-64cb7ff1b278.png)

I'll use the mui icon and style similiar to the send button

**Comment by mssiegel** [comment]
I don't want the button to distract from the chat itself.  Each student will click it a max of one time per chat.  So I think the button should appear above the student's chatbox, within the dark red background.  It sould say "Copy chat (copy_icon)".
