### ISSUE TITLE
Better welcome message when student enters classroom

### ISSUE THREAD

**Issue by mssiegel** [mssiegel/frempco-client#97]
When a student enters the classroom, they see a nearly blank page with text that just welcomes them. We should add a message that says the next step is for the teacher to pair them.  

Example: 
![image](https://user-images.githubusercontent.com/29524485/159924214-ac49765f-e6d8-4686-9869-5f11305b11be.png)

**Comment by karlrez** [comment]
What I noticed with this is we can also get the blank page when the teacher removes a student from the classroom.
For that scenario should we change the message to something like "Your teacher has removed you from the classroom" ?

**Comment by mssiegel** [comment]
Yes! Thats a great idea!!!

**Comment by karlrez** [comment]
Sorry! I actually see now that message is already included:

![image](https://user-images.githubusercontent.com/47090434/160262590-ad5f69fc-896a-4ffe-8a2e-30846a7df0b1.png)

Should we move the "teacher has removed you" into the box below? Or just remove the box and leave the page empty if the student is removed?

**Comment by mssiegel** [comment]
Right now with just a single line of text the page looks empty and it looks kinda wierd. The box fills in the space a bit more. When a student enters the classroom, they should know they did it successfully and that they'll start chatting once a teacher pairs them.

I was thinking for regular students it should say `Hello student_name` where it currently does.
And inside the box it would say in 2 lines:  
`Welcome to your classroom: classroom_name`
`Your teacher will pair you soon.`

And for removed students, it would still save `Hello student_name` above.  
And inside the box it would say in 2 lines:
`Your teacher has removed you from the classroom`
`Please return to the Frempco homepage (link to homepage)`
(If we include a link to the Frempco homepage, we'll have to make sure it logs out the student from the userContext. Or just use an `<a>` tag so it reloads the website fresh.)

Those were my thoughts but feel free to do whatever you think works best!
