### ISSUE TITLE
Refactor authentication for client side pages

### ISSUE THREAD

**Issue by mssiegel** [mssiegel/frempco-client#98]
We are restricting non-logged in users from accessing the classroom pages using code in [_app.tsx](https://github.com/mssiegel/frempco-client/blob/main/pages/_app.tsx#L25-L39)

We could refactor this code to its own component by following the example in this article: https://azeezatraheem.medium.com/implementing-authentication-redirects-in-next-js-c15907ec82b7

**Comment by karlrez** [comment]
I've read through the article and got a working draft of this now. I've added these two files:

- _/pages/protectedRoutes/appRoutes.tsx_ - file with a list of our two routes

- _/pages/protectedRoutes/ProtectedRoutes.tsx_ - component that handles the authentication

Do you have any suggestions on if either file should be moved somewhere else? Or more appropriate file names?

**Comment by mssiegel** [comment]
Great questions and thanks for taking this one! I don't think we need two files. I think there could be just a single file under `/src/routes/CheckAuthentication.tsx`. And it could contain the hardcoded list of student classroom and teacher classroom routes. Those are the only routes that need authentication.  

You'd then import that file into `/pages/_app.tsx`.  I prefer the name `CheckAuthentication` over `ProtectedRoutes`. I feel it better communicates what the component does. Its clear whats happening when you see `<CheckAuthenication>` wrapping the rest of your components in `_app.tsx`

Over the long term future, I expect there to be many more static unprotected routes than protected routes.  I see us eventually having a contact page, an about page, a teacher FAQ page etc.  So we should just store the list of protected routes.

Also, the article mentions an `isBrowser()` function. It could be my knowledge of NextJS is limited, but I don't understand why it's necessary. So feel free to ignore it unless you know why it'd be useful. 

Helpful tip: when you put in `_app.tsx` I think the `UserProvider` will have to go on the outside and wrap `CheckAuthentication`. This is because the `UserContext` has to be instantiated first before the `CheckAuthentication` can import and start using it

For future reference: You can always create a **draft** GitHub PR. This is when you want feedback on code but its not ready for a real PR.
