### ISSUE TITLE
Refactor homepage code to its own component

### ISSUE THREAD

**Issue by mssiegel** [mssiegel/frempco-client#99]
All the homepage code lives in `/pages/index.tsx`

This code should be moved to `src/components/pages/HomePage/index.tsx` just like it currently does for the rest of our pages.

**Comment by karlrez** [comment]
I could take this one if available?
I figure everything inside the <main> tags would be good to move over to a HomePage component?

**Comment by mssiegel** [comment]
If its assigned to no one it means no one is working on it : )
Assign it to yourself and that makes it exclusively yours to work on.

Correct about the `<main>` tags. Its exactly the same as we already did for the `TeachersPage` and `StudentsPage`
